version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appdb


  app:
    build: .
    ports:
      - "3002:3000"
    environment:
    - APP_VERSION=${APP_VERSION}
    depends_on:
      - mysql